train:
	for i in 1 2 3 4 5 6 7 8 9 10 ; do \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 35 --lr 5 --log-interval 2000 --batch_size 1 --data './data/ptb' --upperweight 0.1 --lowerweight -0.1 --seed 1111 ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 60 --lr 5 --log-interval 2000 --batch_size 3 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 100 --lr 5 --log-interval 2000 --batch_size 5 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 200 --lr 5 --log-interval 2000 --batch_size 10 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 300 --lr 5 --log-interval 2000 --batch_size 15 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 400 --lr 5 --log-interval 2000 --batch_size 20 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 500 --lr 5 --log-interval 2000 --batch_size 25 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 600 --lr 5 --log-interval 2000 --batch_size 30 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 700 --lr 5 --log-interval 2000 --batch_size 35 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 1000 --lr 5 --log-interval 2000 --batch_size 50 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 2000 --lr 5 --log-interval 2000 --batch_size 100 --data './data/ptb' ; \
		python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 4000 --lr 5 --log-interval 2000 --batch_size 200 --data './data/ptb' ; \
	done 

run: 
	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 40 --lr 20 --log-interval 2000 --batch_size 1 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 40 --lr 20 --log-interval 2000 --batch_size 1 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 200 --lr 20 --log-interval 2000 --batch_size 5 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 200 --lr 20 --log-interval 2000 --batch_size 5 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 400 --lr 20 --log-interval 2000 --batch_size 10 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 400 --lr 20 --log-interval 2000 --batch_size 10 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	#python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 600 --lr 20 --log-interval 2000 --batch_size 15 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	#python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 600 --lr 20 --log-interval 2000 --batch_size 15 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 800 --lr 20 --log-interval 2000 --batch_size 20 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 800 --lr 20 --log-interval 2000 --batch_size 20 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	#python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 1000 --lr 20 --log-interval 2000 --batch_size 25 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	#python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 1000 --lr 20 --log-interval 2000 --batch_size 25 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 1200 --lr 20 --log-interval 2000 --batch_size 30 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 1200 --lr 20 --log-interval 2000 --batch_size 30 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	#python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 1400 --lr 20 --log-interval 2000 --batch_size 35 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	#python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 1400 --lr 20 --log-interval 2000 --batch_size 35 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 2000 --lr 20 --log-interval 2000 --batch_size 50 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 2000 --lr 20 --log-interval 2000 --batch_size 50 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 1600 --lr 20 --log-interval 2000 --batch_size 40 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 1600 --lr 20 --log-interval 2000 --batch_size 40 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \

	#CUDA_VISIBLE_DEVICES=0 python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 8000 --lr 4 --log-interval 2000 --batch_size 200 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 1111 ; \

	#CUDA_VISIBLE_DEVICES=0 python2 main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 8000 --lr 4 --log-interval 2000 --batch_size 200 --data './data/ptb' --upperweight 0.1 --lowerweight 0.03 --seed 2222 ; \
